kind = "DojoModel"
class_hash = "0x7e288b2545c36cc1306b5da6472e6030b7fe22db72fbef87fda4fbe50a33df1"
original_class_hash = "0x7e288b2545c36cc1306b5da6472e6030b7fe22db72fbef87fda4fbe50a33df1"
abi = "manifests/dev/abis/base/models/renamer_models_index_player.json"
name = "renamer::models::index::player"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "name"
type = "felt252"
key = false
