kind = "DojoContract"
class_hash = "0xffe6f18132208f312c4045a63d6b3ed5b5284a8e8d6c73c8e2ab0eb2e6cae6"
original_class_hash = "0xffe6f18132208f312c4045a63d6b3ed5b5284a8e8d6c73c8e2ab0eb2e6cae6"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/renamer_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "renamer::systems::actions::actions"
