kind = "DojoContract"
class_hash = "0x39725b1db5c7c5df50f569c5bb08973454a3236d5aad360324adb1c898dffd3"
original_class_hash = "0x39725b1db5c7c5df50f569c5bb08973454a3236d5aad360324adb1c898dffd3"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/renamer_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "renamer::systems::actions::actions"
